# Generated by Django 5.1.3 on 2024-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_history', models.JSONField()),
                ('prompt_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
    ]
