# Generated by Django 5.1 on 2024-11-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_message_conversation_remove_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
